### PR TITLE
`openstreetmap_carto` is broken, `data_natural_earth_version` has changed

### PR DESCRIPTION
**Pull request by hummeltech**
https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip 
does not support versioned queries

### CODE REVIEW

**Comment by hummeltech** [comment]
The only solution I can come up with is we could download the files directly from `github` by tag and zip them up.

https://github.com/nvkelso/natural-earth-vector/tree/v5.1.2/110m_cultural

**Comment by hummeltech** [comment]
Or better yet, move all the data into its own RPM

**Review by jbronn — APPROVED** [review]
LGTM, but was this the reason for the Mapnik patch from #43?

**Comment by hummeltech** [comment]
Hmm, there weren't any `mapnik` patches, maybe you meant the `python-mapnik` patches? We might want to just remove `python-mapnik`, as far as I can tell, it's not being used any longer and was only ever experimental anyhow.

Python implementation was dropped:
https://github.com/openstreetmap/mod_tile/commit/bb1782300d4b7d0ea653dca9ee4ed3ae1e813881

**Pull request merged**
