### PR TITLE
GDAL 3.8.0 [Stage 1]

### PR DESCRIPTION
**Pull request by jbronn**
* GDAL 3.8.0 upgrade for EL7 and EL9.
  * Upgrade GEOS to 3.11.3 and FileGDBAPI to 1.5.2 on EL7.
* Because other packages link to GDAL the upgrade has to be in multiple "stages" (e.g., must have GDAL 3.8.0 available in a repository to build PostGIS and Mapnik).
  * The first stage is to build GDAL 3.8.0 and push to a repository, the second stage is a separate branch with updated package iterations pointing to the repository created here.

### CODE REVIEW

**Review by hummeltech — APPROVED** [review]
Nice!
:+1:

**Comment by jbronn** [comment]
* EL9 packages have been signed & published.
* EL7 packages are going to be kept in `staging` channel until dependent applications (Hootenanny) are ready; once that's complete we'll promote to `stable`.

**Review by bmarchant — APPROVED** [review]
Looks great!

**Comment by hummeltech** [comment]
My desktop doesn't even have GDAL v3.8.0 yet!

**Pull request merged**
