### PR TITLE
PostGIS Updates

### PR DESCRIPTION
**Pull request by jbronn**
* [3.2.3](https://postgis.net/2022/08/18/postgis-patches/) on EL7
* [3.3.1 release](https://postgis.net/2022/09/10/postgis-3.3.1/) on EL9

### CODE REVIEW

**Comment by jbronn** [comment]
Ugh, PostgreSQL released [15 Beta 4 yesterday](https://www.postgresql.org/about/news/postgresql-15-beta-4-released-2507/) which [reverted some JSON features](https://github.com/postgres/postgres/commit/96ef3237bf741c12390003e90a4d7115c0c854b7) that is now breaking building PostGIS.  Now we'll have to wait for upstream PostGIS to fix this new regression, as 3.3.0 is supposed to optimized for PostgreSQL 15.

**Comment by hummeltech** [comment]
It looks like they've addressed the issue you stubbed your toe on.
https://postgis.net/2022/09/10/postgis-3.3.1/

**Comment by jbronn** [comment]
@hummeltech thanks for the tip; I've rebased this PR with updated versions.

**Review by hummeltech — APPROVED** [review]

**Review by BuechnerGIS — APPROVED** [review]
:+1:

**Pull request merged**
